In [1]:
import numpy as np


In [3]:
a = np.arange(6)

In [4]:
print(a)

[0 1 2 3 4 5]


In [6]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
b2 = np.arange(12)
b2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
np.zeros(10,dtype = float)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
c = np.arange(25).reshape(5,5)

In [12]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
np.ones((3,5),dtype = float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
c.shape

(5, 5)

In [17]:
c.dtype

dtype('int32')

In [24]:
A = np.array([[2,3],[4,5]])

In [25]:
A

array([[2, 3],
       [4, 5]])

In [26]:
B = np.array([[2,1],[3,4]])
B

array([[2, 1],
       [3, 4]])

In [27]:
A*B

array([[ 4,  3],
       [12, 20]])

In [28]:
A.dot(B)

array([[13, 14],
       [23, 24]])

In [29]:
b = np.arange(12).reshape(3,4)

In [30]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b*=3

In [32]:
b


array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [33]:
b.sum()

198

In [34]:
b.min()


0

In [35]:
b.max()

33

In [36]:
b.sum(axis=0)

array([36, 45, 54, 63])

In [37]:
b.sum(axis=1)

array([ 18,  66, 114])

In [39]:
np.random.random((3,3))

array([[ 0.8441316 ,  0.62672535,  0.22879806],
       [ 0.75219823,  0.39266684,  0.88459436],
       [ 0.51567975,  0.14976883,  0.14823507]])